Repository spryker-sdk/spryk, pull requests merged in 2021-05, with the labels that each got.

#60 TE-9126 Updated composer.json template
  .editorconfig
  composer.json
  config/spryk/templates/composer.json.twig
Labels: improvement, ready-for-release

#61 TE-9104 CI replacement
  .gitattributes
  .githook
  .github/workflows/ci.yml
  .gitignore
  .scrutinizer.yml
  ci/travis.php.ini
  composer.json
  config/spryk/spryks/Spryker/AddModule.yml
  config/spryk/spryks/Spryker/AddModuleCi.yml
  config/spryk/templates/README.md.twig
  config/spryk/templates/ci.yml.twig
  config/spryk/templates/gitattributes.twig
  config/spryk/templates/travis.yml.twig
  generated/spryk_argument_list.yml
  phpstan.neon
  src/SprykerSdk/Spryk/Model/Spryk/Filter/SingularizeFilter.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleCiTest.php
  tests/_data/.gitignore
  tests/_data/src/Pyz/Zed/FooBar/Communication/Controller/IndexController.php
Labels: merge-only, ready-for-release

#64 Fix tests and phpstan
  README.md
  phpstan.json
  phpstan.neon
  src/SprykerSdk/Spryk/Console/SprykRunConsole.php
  src/SprykerSdk/Spryk/Model/Spryk/Definition/Argument/Resolver/OptionsContainer.php
  src/SprykerSdk/Spryk/Model/Spryk/Dumper/SprykDefinitionDumper.php
  src/SprykerSdk/Spryk/Model/Spryk/Dumper/SprykDefinitionDumperInterface.php
  src/SprykerSdk/Spryk/Style/SprykStyle.php
  src/SprykerSdk/Spryk/Style/SprykStyleInterface.php
  tests/SprykerSdkTest/Spryk/Console/SprykRunArgumentCallbackTest.php
  tests/SprykerSdkTest/Spryk/Console/SprykRunTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleChangelogTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleCodeceptionConfigurationTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleComposerJsonTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleContributingTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleCoverallsTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleGitattributesTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleGitignoreTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleLicenseTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModulePhpStanJsonTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModulePhpStanNeonTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleReadmeTest.php
  tests/SprykerSdkTest/Spryk/Integration/AddModuleScrutinizerTest.php
  tests/SprykerSdkTest/Spryk/Integration/Glue/Dependency/Client/AddGlueDependencyClientBridgeInterfaceMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Glue/Dependency/Client/AddGlueDependencyClientBridgeMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Glue/Dependency/Client/AddGlueDependencyClientBridgeTest.php
  tests/SprykerSdkTest/Spryk/Integration/Yves/Dependency/Client/AddYvesDependencyClientBridgeInterfaceMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Yves/Dependency/Client/AddYvesDependencyClientBridgeMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Yves/Dependency/Client/AddYvesDependencyClientBridgeTest.php
  tests/SprykerSdkTest/Spryk/Integration/Yves/Dependency/Service/AddYvesDependencyServiceBridgeInterfaceMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Yves/Dependency/Service/AddYvesDependencyServiceBridgeMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Yves/Dependency/Service/AddYvesDependencyServiceBridgeTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/AddZedTestSuiteToCodeceptionConfigurationTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Client/AddZedDependencyClientBridgeInterfaceMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Client/AddZedDependencyClientBridgeMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Client/AddZedDependencyClientBridgeTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Facade/AddZedDependencyFacadeBridgeInterfaceMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Facade/AddZedDependencyFacadeBridgeMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Facade/AddZedDependencyFacadeBridgeTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Service/AddZedDependencyServiceBridgeInterfaceMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Service/AddZedDependencyServiceBridgeMethodTest.php
  tests/SprykerSdkTest/Spryk/Integration/Zed/Dependency/Service/AddZedDependencyServiceBridgeTest.php
  tests/SprykerSdkTest/Spryk/Model/Spryk/Builder/Method/MethodSprykTest.php
  tests/SprykerSdkTest/Spryk/Model/Spryk/Builder/Navigation/NavigationSprykTest.php
  tests/SprykerSdkTest/Spryk/Model/Spryk/Builder/Template/UpdateYmlSprykTest.php
Labels: merge-only, prio, ready-for-release
